name: SonarCloud analysis

on:
  push:
    branches: [ develop, ci-passed, gh-pages ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  UAA-Test-Analysis:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '11'
          cache: 'gradle'
      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.MARKUS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew --no-daemon -Dspring.profiles.active=default,hsqldb -DfailOnPassedAfterRetry=false --no-daemon build sonarqube jacocoTestReport --info
